import { Box, Container, Heading } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
  return (
      <Box>
        <Head>
        <title>Fortify - Increase Your IPFS Permanency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container maxW="container.xl" centerContent>
          <Heading>Hello, World!</Heading>
      </Container>
      </Box>
  )
}
